### ISSUE TITLE
Impossible to override model value with null on variant

### ISSUE THREAD

**Issue by kpkozak** [fortedigital/Styleguide#5]
1. When configuring multiple variants of the component, it's not possible to override value from default model to `null` - there is default property taken. Example:
`Component.styleguide.json`:
```
{
  "model" : {
    "title" : "Component title",
    "text" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  },
  variants: {
    "name": "no text",
    "model": {
      "text": null
    }
  }
}
```

Result: variant "no text" still have the value of `text` property from the default model.

2. When trying to override, the model is overridden from the previous variant, not the base model. Example: 
`Component.styleguide.json`:
```
{
  "model" : {
    "title" : "Component title",
    "text" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  },
  variants: {
    "name": "variant1",
    "model": {
      "title": "Some title",
  },
  {
    "name": "variant2",
    "model": {
      "text": "Short text",
    }
  }
}
```
Result: `variant2`'s model is filled with "Some title" as `title` and "Short text" as `text` properties.
Expected result: In `variant2` the title is taken from base, default model.

**Comment by tomaszmadeyski** [comment]
Fixed in 717190eddf8fc3ed03a74d28556563b6b549516a
